Iter9
iselldonuts/metrics pull request #10
Opened 2024-05-28 10:40 UTC by iselldonuts

2024-05-28 12:42 UTC, s-shpak requested changes

2024-05-28 12:42 UTC, s-shpak commented on cmd/agent/main.go
> +		panic("cannot initialize zap")
Паниковать не надо, используй `Fatal` логгера

2024-05-28 12:42 UTC, s-shpak commented on internal/core/agent.go
> +				gz, err := gzip.NewWriterLevel(&buf, gzip.BestSpeed)
Не ренициализируй gzipWriter каждый раз, используй метод `Reset` для сброса состояни после отправки и инициализируй только один объект этого типа

2024-05-28 12:42 UTC, s-shpak commented on internal/core/agent.go
> +					log.Infof("Unsupported compress level: %v", err)
Это надо логировать на уровне `Error`

2024-05-28 12:42 UTC, s-shpak commented on internal/api/api.go
> +			log.Infof("failed to unmarshal metrics: %v", err)
Логировать надо только неожиданные ошибки (статус >= 500)

2024-05-28 12:42 UTC, s-shpak commented on go.mod
`go.mod` надо обновлять. Посмотри здесь обсуждение, как это можно сделать: https://app.pachca.com/chats/9180496?message=243787071

2024-05-28 12:42 UTC, s-shpak commented on internal/core/archiver.go
> +type Archiver struct {
Кажется, что этот компонент - часть хранилища, потому лучше создать новый тип хранилища (см. комментарий чуть ниже) и инкапсулировать эту логику в него

2024-05-28 12:42 UTC, s-shpak commented on internal/storage/memory/storage.go
По поводу нового типа хранилища:

Хотелось бы, чтобы:

1. Из конструктора хранилища возвращался объект общего интерфейса
2. Существовало две имплементации харинилища - in-memory и файловая
3. Файловое хранилище было оберткой надо in-memory: то есть встаривало бы in-memory при помощи композиции
В итоге сервису должно быть безразлично, сохраняем ли мы данные в файл или нет.

Если что-то непонятно из этого - уточни в пачке

2024-05-28 12:42 UTC, s-shpak commented on cmd/server/main.go
> +		if conf.StoreInterval != 0 {
А что если интервал 0 ? Посмотри спецификацию, там это обсуждается

2024-05-28 12:42 UTC, s-shpak commented on internal/middleware/gzip.go
> +	return c.w.Header()
Если использовать композицию (https://go.dev/doc/effective_go#embedding), то этот метод можно будет не определять

2024-05-28 12:42 UTC, s-shpak commented on internal/middleware/gzip.go
> +		return err //nolint:wrapcheck // leads to unexpected behavior
`c.r` и `c.zr` - независимые ридеры, ошибка при закрытии одного не должна влиять на закрытие другого

2024-05-28 12:56 UTC, iselldonuts commented on cmd/server/main.go
> +		if conf.StoreInterval != 0 {
Да, это пока не сделано

Я сам замысел не понимаю
Не понимаю синхронно с чем нужно делать запись в файл при StoreInterval = 0
Синхронно с каждым обновлением метрики весь стор писать в файл каждый раз? Звучит как бред, но больше идей особо нет пока, буду думать

Спасибо за супер быстрое ревью)

2024-06-04 18:05 UTC, iselldonuts commented on cmd/agent/main.go
> +		panic("cannot initialize zap")
хм, а логгера же еще нет на этот момент
или имеешь ввиду использовать стандартный логгер? только ради этого его импортить?

2024-07-01 04:38 UTC, tmvrus reviewed
Есть небольшие замечания.

2024-07-01 04:38 UTC, tmvrus commented on cmd/agent/main.go
> +		panic(err)
панику имеет смысл бросать если ее кто-то перехватывает, это просто правило хорошего тона. в данном случае лучше
```
println(err)
os.Exit(1)
```

2024-07-01 04:38 UTC, tmvrus commented on cmd/agent/main.go
> +		log.Panic(err)
тут таже история что и выше log.Panic бросает панику в итоге, но ее никто не ловит, по этой причине лучше log.Fatal будет все тоже самое но более явно

2024-07-01 04:38 UTC, tmvrus commented on cmd/server/main.go
> +		log.Panic(err)
та же история Panic->Fatal

2024-07-01 04:38 UTC, tmvrus commented on cmd/server/main.go
> +					_ = s.Save()
ошибки стоит хотя бы логировать, это полезная практика

2024-07-01 04:38 UTC, tmvrus commented on internal/api/api.go
> +	errMetricNotFound = errors.New("metric not found")
Вводить такого рода ошибки имеет смысл в случае когда на их основе строиться какая-то логика. В данном случае они просто хранят строковое значение, большого смысла в этом нет.

2024-07-01 04:38 UTC, tmvrus commented on internal/api/api.go
> +		_ = a.storage.Save()
все же логировать

2024-07-01 04:38 UTC, tmvrus commented on internal/api/api.go
> +			return
выглядит так что клиент прислал что-то отличное от числа, а мы ему отвечает StatusInternalServerError
но обычно на такое отвечают BadRequest

2024-07-01 04:38 UTC, tmvrus commented on internal/api/api.go
> +			return
тоже выглядит как BadRequest

2024-07-01 04:38 UTC, tmvrus commented on internal/api/api.go
> +	_, _ = fmt.Fprintln(w, "</ul>")
на будущее, для таких штук есть byte/string budiler

2024-07-01 04:38 UTC, tmvrus commented on internal/metrics/sender.go
> +func (s *Sender) SendMetric(typ, name, value string) bool {
не вполне понятно зачем отдавать bool наружу, ведь он используется только что бы залогировать что-то,  при этом и в смой ф-и ошибки логируются тоже

2024-07-01 10:24 UTC, iselldonuts commented on internal/metrics/sender.go
> +func (s *Sender) SendMetric(typ, name, value string) bool {
я там на основе успешности в случае counter метрики сбрасываю каунтер
сделал так: убрал дублирование с логированием и обрабатываю успешность только там где надо

2024-07-01 10:24 UTC, iselldonuts commented on internal/api/api.go
> +	_, _ = fmt.Fprintln(w, "</ul>")
переписал

2024-07-01 10:30 UTC, iselldonuts commented on internal/api/api.go
> +		_ = a.storage.Save()
вот тут вопрос возник

у меня в этом случае получается такая же ситуация, что и в SendMetric:
я уже логирую внутри Save'а, если добавить тут, то будет дублирование логов как там было

что сделал: убрал логирование внутри Save'а и логирую только на уровне api

но в целом непонятно, а где правильнее логировать? а то у меня получилось, что в случае SendMetric я логирую максимально внутри, а здесь – как будто бы наоборот выбрал подход

2024-07-01 10:32 UTC, iselldonuts commented on cmd/server/main.go
> +		log.Panic(err)
да, я так изначально и сделал
но смутило то, что линтер начал ругаться на то, что при фатале не будет выполнена defer функция, которая у меня там для logger.Sync() (вроде как в доке написано, что надо обяз. синхронизировать)

я переделал так, не знаю насколько это правильно:

убрал defer и перед фаталом синкую логгер явно

2024-07-02 06:46 UTC, tmvrus approved these changes

2024-07-03 07:55 UTC, merged