Iter5
iselldonuts/metrics pull request #6
Opened 2024-05-07 00:51 UTC by iselldonuts

2024-05-10 13:22 UTC, s-shpak requested changes
Настрой `golangci-lint` для запуска при помощи Github Actions, см. здесь как https://github.com/s-shpak/praktikum-golangci-lint?tab=readme-ov-file#настройка-github-actions. Поправь проблемы, которые линтер обнаружит

Поправь `metricstest` и `statictest` как описано здесь: https://app.pachca.com/chats/9180496?message=230119157

Обрати внимание, что я пометил не все проблемные места в коде: если одна и та же ошибка встречается несколько раз, то надо поправить ее везде

2024-05-10 13:22 UTC, s-shpak commented on cmd/agent/main.go
> +	fmt.Printf(
Используй `log` вместо `fmt`

2024-05-10 13:22 UTC, s-shpak commented on cmd/agent/main.go
> +			time.Sleep(time.Duration(options.pollInterval) * time.Second)
Используй `time.Ticker` (https://pkg.go.dev/time#Ticker) вместо вызовов `Sleep`

2024-05-10 13:22 UTC, s-shpak commented on cmd/agent/main.go
> +	sender := func() {
Не создавай анонимные функции, лучше используй обычные (неэкспортируемые на уровне пакета)

2024-05-10 13:22 UTC, s-shpak commented on cmd/agent/main.go
> +				go doPost(url)
Не надо использовать горутины, просто используй `time.Ticker` + `select`

2024-05-10 13:22 UTC, s-shpak commented on cmd/agent/main.go
> +	time.Sleep(time.Duration(1<<63 - 1))
Используй бесконечный цикл

2024-05-10 13:22 UTC, s-shpak commented on cmd/agent/flags.go
> +		log.Fatal(err)
Так нельзя, смотри видео про ошибки: https://app.pachca.com/chats/9180496?message=234290731

2024-05-10 13:22 UTC, s-shpak commented on cmd/agent/flags.go
> +var options struct {
Глобальные переменные не нужны

2024-05-10 13:22 UTC, s-shpak commented on cmd/agent/main.go
> +func run() {
Очень много кода: в пакете `main` должен лежать только кода запускающий приложение, не более того. Перенеси в `internal`

2024-05-10 13:22 UTC, s-shpak commented on go.mod
> +go 1.21.9
```suggestion
go 1.22.2
```

2024-05-10 13:22 UTC, s-shpak commented on internal/api/api.go
> +		_, _ = fmt.Fprint(w, m)
Почему не `w.Write()` ?

2024-05-10 13:22 UTC, s-shpak commented on internal/storage/memory/storage.go
> +func (m *Storage) String() string {
Зачем это ?

2024-05-10 13:22 UTC, s-shpak commented on internal/metrics/poller.go
> +	m.PollCount = 0
А если отправить метрики не получилось, `PollCount` все равно надо сбросить в `0` ?

2024-05-11 19:37 UTC, iselldonuts commented on internal/metrics/poller.go
> +	m.PollCount = 0
Думаю не надо) Пофиксил

2024-05-11 19:39 UTC, iselldonuts commented on internal/storage/memory/storage.go
> +func (m *Storage) String() string {
Осталось от старого инкремента где нужно было как-то отслеживать хранилище, удалил

2024-05-11 19:40 UTC, iselldonuts commented on internal/api/api.go
> +		_, _ = fmt.Fprint(w, m)
У нас же float64, с w.Write() как я понял пришлось бы конвертить в массив байт каким-то образом вручную

2024-05-11 19:46 UTC, iselldonuts commented on cmd/agent/main.go
> +				go doPost(url)
А разве делать синхронно в цикле серию пост запросов это не есть гуд?
Клиент же синхронно их будет делать как я понимаю, а с отправкой в горутине мы их одновременно бы произвели и одна не дожидалась бы результата другой

Убрал горутину, но не понимаю почему так правильнее

2024-05-13 08:32 UTC, s-shpak commented on cmd/agent/main.go
> +				go doPost(url)
Потому что мы еще не разбирали го-рутины, мы будем добавлять это в следующих спринтах

2024-05-13 08:45 UTC, s-shpak requested changes

2024-05-13 08:45 UTC, s-shpak commented on cmd/server/flags.go
> +var baseURL string
Глобальные переменные не нужны

2024-05-13 08:45 UTC, s-shpak commented on cmd/server/main.go
> +	log.Println("Running server on", baseURL)
```suggestion
	log.Printf("Running server on %s", baseURL)
```

2024-05-13 08:45 UTC, s-shpak commented on cmd/server/main.go
> +	return fmt.Errorf("run error: %w", http.ListenAndServe(baseURL, r))
Посмотри видео про ошибки, в конце я говорю о том, как обрабатывать эту: https://app.pachca.com/chats/9180496?message=234290731

2024-05-13 08:45 UTC, s-shpak commented on internal/api/api.go
> +var s = storage.NewStorage(storage.Config{
Глобальная переменная

2024-05-13 08:45 UTC, s-shpak commented on internal/api/api.go
> +		_, _ = fmt.Fprint(w, m)
Числовые значения необходимо кастовать в строки при помощи `strconv`

2024-05-13 08:45 UTC, s-shpak commented on internal/core/agent.go
> +				_, _ = client.R().
Ошибки и код ответа надо проверять

2024-05-14 13:05 UTC, s-shpak requested changes

2024-05-14 13:05 UTC, s-shpak commented on agent
Этот файл не надо пушить в репозиторий

2024-05-14 14:53 UTC, s-shpak approved these changes

2024-05-14 15:01 UTC, merged